name: Sync Fork

on:
  schedule:
    - cron: '* */24 * * *' # 每天一次
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: imoxuan/TDengine
        with:
          token: ${{ secrets.fork-token }}
          owner: mack-a
          base: master
          head: master
